---
title: "RADS Categorization and Quantification"
author: "Shelby E Andersen"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
library(scrutiny)
library(ggplot2)
library(MetBrewer)
library(ggprism)
```
Read in InterPro Output
```{r}
interpro <- read_tsv("interposcaninput_tsr25bait_bacteroidota.faa.tsv", col_names=c("Accession", "region", "length", "analysis", "signature.accession", "signature.description", "start", "stop", "score", "status", "date", "interpro.accession", "interpro.annotation", "GO", "pathway", "genus"))

```

Generate domain category lists
Note: These will likely need to be edited to fit your dataset. This lists are not all-inclusive.
```{r}
tox_antitox <- c("ANTITOXIN CHPS-RELATED", "Antidote-toxin recognition MazE, bacterial antitoxin", "ENDORIBONUCLEASE TOXIN XHPB-RELATED", "PemK-like, MazF-like toxin of type II toxin-antitoxin system", "Plasmid maintenance toxin/Cell growth inhibitor", "RelB antitoxin", "RelB antitoxin/Antitoxin DinJ", "RelE_StbE: addiction module toxin, RelE/StbE family", "Toxin-antitoxin system, RelE/ParE toxin family", "Bacterial toxin of type II toxin-antitoxin system, YafQ", "Toxin-antitoxin system, YafQ-like toxin", "Toxin HigB-like", "Bacterial epsilon antitoxin", "Antitoxin epsilon/PezA domain superfamily", "Zeta toxin", "HicB_like antitoxin of bacterial toxin-antitoxin system", "HicB-like antitoxin of toxin-antitoxin system", "Antidote-toxin recognition MazE, bacterial antitoxin", "Putative Holin-like Toxin (Hol-Tox)", "holin_tox_secr: toxin secretion/phage lysis holin", "TOXIN RELE", "Toxin ToxN, type III toxin-antitoxin system", "MRNA INTERFERASE TOXIN YAFQ", "Fido domain-containing protein", "Fido-like domain superfamily", "LysM domain superfamily", "Pectin lyase fold/virulence factor", "Virulence protein RhuM-like", "Toxin-antitoxin system, RelE/ParE toxin domain superfamily", "Nucleotidyl transferase AbiEii toxin, Type IV TA system", "PIN family, putative toxin-antitoxin system toxin component", "PIN-like domain superfamily", "PIN domain", "Antidote-toxin recognition MazE, bacterial antitoxin", "PemK-like, MazF-like toxin of type II toxin-antitoxin system", "MazF", "mRNA interferase PemK-like", "LysM domain")

CBASS <- c("Adenylyl/Guanylyl and SMODS C-terminal sensor domain", "SMODS-associated NUDIX domain", "NUDIX domain", "NUDIX hydrolase domain", "Nudix_Hydrolase_18", "NUDIX hydrolase family signature", "Nudix", "NUDIX hydrolase-like domain superfamily", "SMODS- and Ubiquitin system-associated 2TM effector domain", "SMODS/Ubiquitin system-associated 2TM effector domain", "Cyclic nucleotide-binding domain superfamily", "Cyclic nucleotide-binding domain", "Nucleotide cyclase", "Reverse transcriptase/Diguanylate cyclase domain", "Toll/interleukin-1 receptor homology (TIR) domain superfamily")

RM <- c("HNH nuclease", "Ribonuclease H-like", "Ribonuclease H-like superfamily", "TYPE I SITE-SPECIFIC DEOXYRIBONUCLEASE PROTEIN SUBUNIT M AND R", "Restriction endonuclease, type I, HsdR, N-terminal", "ENDORIBONUCLEASE TOXIN CHPB-RELATED", "ENDORIBONUCLEASE MAZF-RELATED", "GIY-YIG endonuclease superfamily", "GIY-YIG endonuclease", "hsdR: type I site-specific deoxyribonuclease, HsdR family", "Restriction endonuclease type I, HsdR", "Restriction endonuclease type I, HsdR, N-terminal", "Relaxase/Mobilisation nuclease domain", "Endonuclease relaxase, MobA/VirD2", "tRNA endonuclease-like domain superfamily", "MvaI/BcnI restriction endonuclease, catalytic domain", "MvaI/BcnI restriction endonuclease family", "MvaI/BcnI restriction endonuclease, recognition domain", "NgoFVII restrictoin endonuclease", "Restriction endonuclease, type II, NgoFVII", "Putative endonuclease, Z1 domain", "DDE superfamily endonuclease", "phage-Barnase-EndoU-ColicinE5/D-RelE like nuclease4", "Restriction endonuclease type IV, Mrr", "Restriction endonuclease-like", "Restriction endonuclease type II-like", "ATP-DEPENDENT ENDONUCLEASE, OLD FAMILY-RELATED", "Ribonuclease Z/Hydroxyacylglutathione hydrolase-like", "Restriction endonuclease, type II, Alwl", "Extracellular Endonuclease, Subunity A", "DNA/RNA non-specific endonuclease superfamily","DDE superfamily endonuclease", "Thermonuclease domain profile", "Staphylococcal nuclease (SNase-like), OB-fold", "Staphylococcal nuclease homologue", "Staphylococcal nuclease", "Thermonuclease family signature 2", "Thermonuclease active site", "Type I restriction modification DNA specificity domain", "N4/N6-methyltransferase, Type III restriction-modification enzyme EcoPI Mod subunit-like", "DNA mismatch repair MutH/Type II restriction endonuclease superfamily", "P-loop containing nucleoside triphosphate hydrolase", "P-loop containing nucleoside triphosphate hydrolases", "DNA methylase, N-6 adenine-specific, conserved site", "MobA/VirD2-like, nuclease domain", "S-adenosyl-L-methionine-dependent methyltransferase superfamily", "RadC-like JAB domain", "Ribonuclease II/R", "(Uracil-5)-methyltransferase family", "Type II methyltransferase M.TaqI-like domain", "Nuclease associated modular domain 3", "PD-(D/E)XK endonuclease-like domain superfamily", "RNase II/RNase R, cold shock domain", "Ribonuclease R", "C-5 cytosine methyltransferase", "MobA/MobL protein", "MobA/VirD2-like, nuclease domain", "Ribonuclease H superfamily", "Homing endonuclease associated repeat", "Ribonuclease J, bacteria", "OLD protein-like, TOPRIM domain", "Orc1-like, AAA ATPase domain", "Methyltransferase small domain", "N6 adenine-specific DNA methyltransferase, N-terminal domain", "Intron endonuclease, group I", "BREX protein BrxB", "BrxA", "BrxA superfamily", "Type ISP restriction-modification enzyme LLaBIII, C-terminal specificity domain", "Ribonuclease J", "Ribonuclease J, C-terminal", "Ribonuclease J, domain 2", "HNH endonuclease 5", "Endopeptidase, NLPC/P60 domain", "Exonuclease, RNase T/DNA polymerase III", "DNA methylase N-4/N-6", "Orc1-like, AAA ATPase domain", "Ribonuclease J, bacteria", "TYPE I RESTRICTION ENZYME ECOKI R PROTEIN", "Type III restriction enzyme, res subunit", "ENDORIBONUCLEASE MAZF-RELATED", "Nucleotide-diphospho-sugar transferases", "N-terminal domain of anti-restriction factor ArdC", "Glycosyl transferase, family 1", "Antirestriction, ArdC", "Glycosyltransferase 2-like", "Retron Ec78 putative HNH endonuclease-like", "DNA methylase, adenine-specific", "Glycosyltransferase subfamily 4-like, N-terminal domain", "Methylase domain")

Abi <- c("Bacteriophage abortive infection AbiH", "Transcriptional regulator, AbiEi antitoxin", "Nucleotidyl transferase AbiEii toxin, type IV TA system", "Abi-like protein", "Abortive infection system protein AbiD/AbiF-like", "ToxN/AbiQ toxin", "AbiU2", "AAA domain, putative AbiEii toxin, Type IV TA system", "Abortive infection system protein AbiD/AbiF", "HEPN, AbiU2-like")

Transposase <- c("Transposases, Mutator family, signature.", "Transposase, mutator type", "TRANSPOSASE FOR INSERTION SEQUENCE ELEMENT IS1081", "TRANSPOSASE INSN FOR INSERTION SEQUENCE ELEMENT IS911A-RELATED", "Transposase", "Transposase IS3/IS911family", "TRANSPOSASE INSF FOR INSERTION SEQUENCE IS3B-RELATED", "TRANSPOSASE INSF FOR INSERTION SEQUENCE IS3B", "Transposase InsF-like", "Mu transposase, C-terminal", "TRANSPOSASE, PUTATIVE-RELATED", "mu transposase, C-terminal", "Tc1-like transposase, DDE", "TRANSPOSABLE ELEMENT-RELATED", "Tn3 transposase DDE domain", "Transposase SI200 like", "Transposase IS200-like", "Transposase, IS4-like", "Transposase Inhibitor Protein From Tn5; Chain A, domain 1", "TRANSPOSASE INSL FOR INSERTION SEQUENCE ELEMENT IS186A-RELATED", "Transposase IS204/IS1001/IS1096/IS1165, DDE domain", "Helix-turn-helix domain of transposase family ISL3", "Transposase IS204/IS1001/IS1096/IS1165, helix-turn-helix domain", "Transposase IS30-like HTH domain", "TRANSPOSASE", "TRANSPOSABLE ELEMENT-RELATED", "Transposase domain (DUF772)", "Transposase InsH, N-terminal", "IS1478 TRANSPOSASE", "Transposase, IS30, conserved site", "Putative transposase of IS4/5 family (DUF4096)", "Putative transposase IS4/IS5 family", "Zinc-finger of transposase IS204/IS1001/IS1096/IS1165", "Transposase IS204/IS1001/IS1096/IS1165, zinc-finger", "Transposase IS701-like, DDE domain", "Probable transposase", "Probable transposase, IS891/IS1136/IS1341", "tspaseT_teng_C:transposase,IS605 OrfB family", "Transposase IS605, ORfB, C-terminal", "TRANSPOSASE FOR INSERTION SEQUENCE ELEMENT IS1111A", "Transposase, IS116/IS110/IS902", "Transposase IS3/IS911family", "Transposase IS200-like superfamily", "Transposon-encoded protein TnpV", "Excisionase from transposon Tn916", "Transposon Tn1545/Tn916, excisionase", "Transposase IS4-like domain", "Transposase, putative, helix-turn-helix domain", "IS6 family transposase", "IS5 family transposase", "Transposase IS116/IS110/IS902, C-terminal", "Transposase DDE domain", "Transposase ISL3", "IS4 family transposase", "Excisionase from transposon Tn916", "Conjugative transposon, TraN", "Conjugative transposon, TraM", "Conjugative transposon, TraK")

DUFs1 <- c("Family of unknown function (DUF5677)", "Family of unknown function DUF5677", "Protein of unknown function (DUF805)", "Protein of unknown function DUF805", "Protein of unknown function (DUF2786)", "Domain of unknown function DUF2786", "Domain of unknown function (DUF1906)", "Protein of unknown function DUF1906", "Protein of unknown function C-terminal (DUF3324)", "Domain of unknown function DUF3324, C-terminal", "Bacterial protein of unknown function (DUF916)", "Protein of unknown function DUF916, cell surface putative", "Uncharacterized conserved protein (DUF2075)", "Protein of unknown function DUF262", "Domain of unknown function DUF262", "Protein of unknown function (DUF3021)", "Repeat of unknown function (DUF5648)", "Repeat of unknown function DUF5648", "Domain of unknown function (DUF3650)", "Domain of unknown function DUF3850", "Family of unknown function (DUF6290)", "Protein of unknown function DUF6290", "Protein of unknown function (DUF2786)", "Domain of unknown function DUF2786", "Protein of unknwon function DUF4355", "Protein of unknown function DUF2273", "Protein of unknown function DUF2759", "Protein of unknown function DUF2626", "Uncharacterised protein family UPF0236", "Protein of unknown function DUF998", "Protein of unknown function DUF917, N-terminal", "Protein of unknown function DUF2933", "Protein of unknown function DUF6442", "Protein of unknown function DUF2800", "Domain of unknown function DUF3825", "Protein of unknown function DUF3781", "Domain of unknown function DUF1524", "Protein of unknown function DUF6339", "Protein of unknown function DUF2130", "Protein of unknown function DUF1093", "Protein of unknown function DUF915, hydrolase-like", "Protein of unknown function DUF4176", "Protein of unknown function DUF308, membrane", "Protein of unknown function DUF2933", "Protein of unknown function DUF1906", "Protein of unknown function DUF1413", "Protein of unknown function DUF975", "Protein of unknown function DUF697", "Domain of unknown function DUF2687", "Domain of unknown function DUF305", "Domain of unknown function DUF2382", "Domain of unknown function DUF5937", "Protein of unknown function DUF2538", "Protein of unknown function DUF5966", "Protein of unknown function DUF5962", "Protein of unknown function DUF5965", "Protein of unknown function DUF5945", "Domain of unknown function DUF3991", "Protein of unknown function DUF4250", "Uncharacterised protein family UPF0597", "Family of unknown function DUF5688", "Protein of unknown function DUF4406", "Domain of unknown function DUF4368", "Domain of unknown function DUF5348	13	Other", "Protein of unknown function DUF6462", "Protein of unknown function DUF932", "Uncharacterised protein family UPF0758", "Uncharacterised protein family UPF0758, conserved site")
DUFs2 <- c("Protein of unknown function DUF413", "Protein of unknown function DUF4956", "Protein of unknown function DUF486", "Protein of unknown function DUF4391", "Protein of unknown function DUF4317", "Protein of unknown function DUF4276", "Protein of unknown function DUF4248", "Protein of unknown function DUF3791", "Protein of unknown function DUF3592", "Protein of unknown function DUF3575", "Protein of unknown function DUF3368", "Protein of unknown function DUF3102", "Protein of unknown function DUF2971", "Protein of unknown function DUF2812", "Protein of unknown function DUF2508", "Protein of unknown function DUF2089", "Protein of unknown function DUF1700", "Protein of unknown function DUF1643", "Protein of unknown function DUF1275", "Domain of unknown function DUF6273", "Domain of unknown function DUF6440", "Domain of unknown function DUF6591", "Domain of unknown function DUF6017", "Domain of unknown function DUF5979", "Domain of unknown function DUF58", "Domain of unknown function DUF4435", "Domain of unknown function DUF4352", "Domain of unknown function DUF4340", "Domain of unknown function DUF4261", "Domain of unknown function DUF4158", "Domain of unknown function DUF4143", "Domain of unknown function DUF4113", "Domain of unknown function DUF4062", "Domain of unknown function DUF3991", "Domain of unknown function DUF2262", "Domain of unknown function DUF1858", "DUF1980, C-terminal domain", "DUF11 repeat", "Protein of unknown function DUF4230", "Protein of unknown function DUF960", "Protein of unknown function DUF1836", "Protein of unknown function DUF3990", "Domain of unknown function DUF304", "Domain of unknown function DUF6311", "Protein of unknown function DUF3847", "Domain of unknown function DUF3848", "Family of unknown function (DUF5688)", "Transposase domain (DUF772)", "Uncharacterised protein family UPF0758", "Uncharacterised protein family UPF0758, conserved site", "Protein of unknown function DUF4134", "Domain of unknown function DUF4368", "Domain of unknown function DUF4435", "Protein of unknown function DUF486", "Protein of unknown function DUF308, membrane", "Protein of unknown function DUF960", "Uncharacterised protein family UPF0251", "Domain of unknown function DUF4988", "Protein of unknown function DUF4858", "Domain of unknown function DUF234", "Protein of unknown function DUF3847", "Domain of unknown function DUF304", "Domain of unknown function DUF3945", "Protein of unknown function DUF1836", "Domain of unknown function DUF4143")

Recombinase <- c("Resolvase/invertase-type recombinase catalytic domain profile.", "Resolvase, N-terminal catalytic domain", "Resolvase-like N-terminal catalytic domain superfamily", "resolvase_6", "Resolvase, HTH domain", "Helix-turn-helix domain of resolvase", "Site-specific recombinases active site.", "Recombinase, conserved site", "SERINE RECOMBINASE PINE-RELATED", "Site-specific recombinases signature 2", "Plasmid recombination enzyme", "DNA recombination and repair protein RecA, monomer-monomer interface")
```

Assign categories to domain entries in InterPro data
```{r}
interpro$Category <- ifelse(interpro$interpro.annotation %in% tox_antitox, "ToxinAntitox",
                                     ifelse(interpro$interpro.annotation %in% CBASS, "CBASS",
                                            ifelse(interpro$interpro.annotation %in% tox_antitox, "Toxin/Antitox",
                                                   ifelse(interpro$interpro.annotation %in% RM, "Restriction Enzyme",
                                                          ifelse(interpro$interpro.annotation %in% Abi, "Abortive Infection",
                                                                 ifelse(interpro$interpro.annotation %in% Transposase, "Transposase",
                                                                        ifelse(interpro$interpro.annotation %in% DUFs1, "DUF", 
                                                                               ifelse(interpro$interpro.annotation %in% DUFs2, "DUF",""))))))))
```

Generate dataframe with category counts
```{r}
interproaabundance <- interpro %>% group_by(Category) %>% summarise(n=n()) %>% filter(Category != "")
```

Generate plot with abundance of categories
```{r}
ggplot(interprophylaabundanceforggplot, aes(x=Category, y=n)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values=met.brewer("Veronese", 7)) +
  theme_prism() +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, size = 12, vjust=0.5), axis.text.y = element_text(size = 12), axis.title.x = element_blank()) +
  labs(y="n") +
  scale_y_continuous(expand=c(0,0))
```